name: 🚀 Auto FTP Deploy to Subdomain

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Deploy to FTP (Subdomain)
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./
          server-dir: /home/nebosha1/app.nebosh-azurewebsites.com/  # Path to your subdomain
